name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: deno install

      - name: Build project
        env:
          DISCORD_KEY: ${{ secrets.DISCORD_KEY }}
          CHAT_WEBHOOK: ${{ secrets.CHAT_WEBHOOK }}
          FEEDBACK_WEBHOOK: ${{ secrets.FEEDBACK_WEBHOOK }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
        run: deno task build

      - name: Upload
        env:
          VAL_KEY: ${{ secrets.VAL_KEY }}
        run: deno task upload

  check-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: deno install

      - name: Check
        run: deno task check

      - name: Lint
        run: deno task lint
